function r = plot_front(RTMflow_class,t_index)

for j = 1:length(RTMflow_class.edge_data{t_index})
    plot([RTMflow_class.Delaunay_mesh_class.nodes(RTMflow_class.edge_data{t_index}(j,2),1), ...
              RTMflow_class.Delaunay_mesh_class.nodes(RTMflow_class.edge_data{t_index}(j,3),1)],...
             [RTMflow_class.Delaunay_mesh_class.nodes(RTMflow_class.edge_data{t_index}(j,2),2), ...
              RTMflow_class.Delaunay_mesh_class.nodes(RTMflow_class.edge_data{t_index}(j,3),2)], ...
             'k-','LineWidth',2);
end
r = 0;
end